[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
echo = "GaKTW6ycDT2yeAbN7siKdJTw9Xz777DpR5uXMMuw4CQZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vnr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
